/**
 * Brand & content configuration — single source of truth for every visible string.
 * Stage 4 demo build (generated by stage4_build.py) reskinned from the Palmshades
 * eyewear base for the scraped TikTok business @visionspacegh_.
 */
import type { SeedName } from "@cimplify/sdk/testing/suite";

export interface BrandSocial {
  label: string;
  href: string;
  icon?: "instagram" | "x" | "tiktok" | "facebook" | "youtube" | "linkedin" | "whatsapp";
}
export interface BrandFaqEntry { q: string; a: string; }
export interface BrandFaqSection { title: string; items: BrandFaqEntry[]; }
export interface BrandPolicySection { heading: string; body: string | { intro: string; bullets: string[] }; }
export interface BrandSitemapSection { title: string; links: { label: string; href: string }[]; }

export interface Brand {
  name: string; shortName: string; microTag: string; description: string;
  schemaType: "Store" | "Bakery" | "Restaurant" | "BeautySalon" | "GroceryStore" | "LocalBusiness" | "Organization";
  currency: string; locale: string;
  contact: { address: string; streetAddress: string; city: string; countryCode: string; phone: string; phoneTel: string; email: string; privacyEmail: string; supportEmail?: string; businessEmail?: string; hours: string; };
  socials: BrandSocial[];
  header: { nav: { label: string; href: string }[] };
  hero: { badge: string; title: string; subtitle: string; primaryCtaLabel: string; secondaryCtaLabel?: string; secondaryCtaHref?: string; };
  trustItems?: { label: string; value: string; description: string; iconKey: string }[];
  brandStrip?: { headline: string; brands: { name: string; domain: string }[] };
  promo?: { badge: string; title: string; body: string; ctaLabel: string; ctaHref: string };
  tradeIn?: { eyebrow: string; title: string; body: string; primaryCtaLabel: string; primaryCtaHref: string; secondaryCtaLabel: string; secondaryCtaHref: string; steps: { step: string; title: string; body: string }[]; };
  newsletter: { eyebrow: string; title: string; body: string; placeholder: string; submitLabel: string; successLabel: string; };
  about: { eyebrow: string; title: string; paragraphs: string[]; sections: { heading: string; body: string }[]; };
  journal: { eyebrow: string; title: string; paragraphs: string[]; };
  faq: { eyebrow: string; title: string; sections: BrandFaqSection[]; contactPrompt: string; contactEmail: string };
  terms: { eyebrow: string; title: string; lastUpdated: string; sections: BrandPolicySection[] };
  privacy: { eyebrow: string; title: string; lastUpdated: string; sections: BrandPolicySection[] };
  shipping: { eyebrow: string; title: string; lastUpdated: string; sections: BrandPolicySection[] };
  returns: { eyebrow: string; title: string; lastUpdated: string; sections: BrandPolicySection[] };
  accessibility: { eyebrow: string; title: string; lastUpdated: string; sections: BrandPolicySection[] };
  account: { loginEyebrow: string; loginTitle: string; loginSubtitle: string; signupEyebrow: string; signupTitle: string; signupSubtitle: string; accountEyebrow: string; accountTitle: string; };
  contactPage: { eyebrow: string; title: string; body: string; reasons: string[]; directLines: { label: string; value: string; href: string }[]; };
  trackOrder: { eyebrow: string; title: string; body: string };
  footer: { blurb: string; sitemap: BrandSitemapSection[]; poweredBy?: { label: string; href: string } };
  llms: { summary: string };
  mock: { seed: SeedName; businessId: string };
  assets: { logo: string; footerLogo: string; hero: string; heroVideo: string; campaign: string[]; hoodedSet: string; summer2026: string[]; denimStory: string; };
  fashion: {
    season: string;
    summer2026: { eyebrow: string; title: string; body: string; primaryCtaLabel: string; primaryCtaHref: string; secondaryCtaLabel: string; secondaryCtaHref: string; signalEyebrow: string; signalTitle: string; imageKicker: string; lookLabel: string; yearMark: string; };
    campaignTitle: string; campaignBody: string;
    categoryHighlight: { eyebrow: string; title: string; items: { slug: string; label: string; blurb: string; href: string; image: string }[]; };
    seenBy: { eyebrow: string; title: string; people: { role: string; name: string; image: string }[]; };
    mensTitle: string; mensBody: string; womensTitle: string; womensBody: string; denimTitle: string; denimBody: string; accessoriesTitle: string; accessoriesBody: string; socialHandle: string;
  };
}

export const brand: Brand = {
  "name": "Vision Space",
  "shortName": "Vision Space",
  "microTag": "VS",
  "description": "Vision Space — an eye clinic near KNUST Campus, Kumasi, for eye tests, frames, and lenses.",
  "schemaType": "Store",
  "currency": "GHS",
  "locale": "en_GH",
  "contact": {
    "address": "Ayeduase, KNUST Campus, Kumasi",
    "streetAddress": "Ayeduase",
    "city": "Kumasi",
    "countryCode": "GH",
    "phone": "+233 59 888 2009",
    "phoneTel": "+233598882009",
    "email": "hello@visionspacegh.gh",
    "privacyEmail": "hello@visionspacegh.gh",
    "supportEmail": "hello@visionspacegh.gh",
    "businessEmail": "hello@visionspacegh.gh",
    "hours": "Mon-Sat 9am-7pm"
  },
  "socials": [
    {
      "label": "TikTok",
      "href": "https://www.tiktok.com/@visionspacegh_",
      "icon": "tiktok"
    },
    {
      "label": "WhatsApp",
      "href": "https://wa.me/233598882009",
      "icon": "whatsapp"
    }
  ],
  "header": {
    "nav": [
      {
        "label": "New arrivals",
        "href": "/shop"
      }
    ]
  },
  "hero": {
    "badge": "EYE CLINIC",
    "title": "See your\nworld clearly.",
    "subtitle": "Eye tests, optical frames, and lenses from a friendly eye clinic near KNUST Campus, Kumasi.",
    "primaryCtaLabel": "Shop the frames",
    "secondaryCtaLabel": "Our story",
    "secondaryCtaHref": "/journal"
  },
  "promo": {
    "badge": "New in",
    "title": "The new frames just landed.",
    "body": "Fresh optical, blue-light, and statement frames — glazed to your prescription on request.",
    "ctaLabel": "Shop the frames",
    "ctaHref": "/shop"
  },
  "tradeIn": {
    "eyebrow": "Frame styling",
    "title": "Find the frame that fits your face.",
    "body": "Send your face shape and the look you're after on WhatsApp. We'll pull a short edit of frames that suit you and help you pick the pair you'll reach for daily.",
    "primaryCtaLabel": "Chat on WhatsApp",
    "primaryCtaHref": "https://wa.me/233598882009",
    "secondaryCtaLabel": "Read the FAQ",
    "secondaryCtaHref": "/faq",
    "steps": [
      {
        "step": "01",
        "title": "Send the brief",
        "body": "Face shape, budget, and the look you want."
      },
      {
        "step": "02",
        "title": "Get the edit",
        "body": "A short pick of frames chosen to suit you."
      },
      {
        "step": "03",
        "title": "Wear them out",
        "body": "Pickup in Kumasi or delivery."
      }
    ]
  },
  "newsletter": {
    "eyebrow": "The list",
    "title": "First look at every drop.",
    "body": "New frame drops, restocks, and styling tips from Vision Space. Short and sweet, no noise.",
    "placeholder": "you@email.com",
    "submitLabel": "Join",
    "successLabel": "You're on the list"
  },
  "about": {
    "eyebrow": "About Vision Space",
    "title": "Eyewear,\nmade to be seen.",
    "paragraphs": [
      "Vision Space is Kumasi's home for eye tests, frames, and lenses.",
      "We pick frames that look premium and fit the way you live — clear, blue-light, or prescription lenses glazed on request.",
      "Honest prices, fast replies, and delivery across Ghana from Kumasi."
    ],
    "sections": [
      {
        "heading": "Fitted to your face",
        "body": "Frames picked by shape and width so they sit balanced all day."
      },
      {
        "heading": "Lenses on request",
        "body": "Clear, blue-light, or prescription lenses glazed to your script."
      },
      {
        "heading": "Visit",
        "body": "Ayeduase, KNUST Campus, Kumasi. Mon-Sat 9am-7pm."
      }
    ]
  },
  "journal": {
    "eyebrow": "Journal",
    "title": "Made in Ghana.\nMade to be seen.",
    "paragraphs": [
      "Vision Space started with a simple idea: good eyewear shouldn't be hard to find or overpriced.",
      "Every frame is chosen for fit, finish, and the way it makes you feel when you put it on.",
      "Fitted to you, delivered to your door."
    ]
  },
  "faq": {
    "eyebrow": "Customer care",
    "title": "Questions, answered.",
    "sections": [
      {
        "title": "Ordering",
        "items": [
          {
            "q": "How do I order?",
            "a": "Message us on WhatsApp or order through the store. We confirm stock and arrange pickup or delivery in Kumasi."
          },
          {
            "q": "Can I pick up in person?",
            "a": "Yes — we're in Kumasi. Message us first to confirm your pair is ready."
          },
          {
            "q": "Do you deliver?",
            "a": "We deliver across Accra and ship regionally. Rates and timing are confirmed when you order."
          }
        ]
      },
      {
        "title": "Frames and lenses",
        "items": [
          {
            "q": "Can I add my prescription?",
            "a": "Yes — most frames can be glazed to your prescription on request. Send us your script and we'll confirm before glazing."
          },
          {
            "q": "What lens options are there?",
            "a": "Clear, blue-light, and prescription lenses, with anti-glare options on selected frames."
          },
          {
            "q": "How do I choose the right size?",
            "a": "Tell us your usual frame or send a photo and we'll guide you to the right fit."
          }
        ]
      },
      {
        "title": "Returns",
        "items": [
          {
            "q": "Can I return a frame?",
            "a": "Unworn frames in original condition can be exchanged within 3 days. Prescription-glazed lenses are made to order."
          },
          {
            "q": "What if my order arrives damaged?",
            "a": "Send us a photo and your order details within 48 hours and we'll make it right."
          }
        ]
      }
    ],
    "contactPrompt": "Still stuck? Message",
    "contactEmail": "hello@visionspacegh.gh"
  },
  "terms": {
    "eyebrow": "Terms",
    "title": "Terms of Service",
    "lastUpdated": "1 June 2026",
    "sections": [
      {
        "heading": "1. Who we are",
        "body": "Vision Space is an eyewear retailer based in Kumasi, Ghana. By placing an order, you agree to these terms."
      },
      {
        "heading": "2. Orders",
        "body": "Orders are accepted once stock and payment are confirmed. We may cancel and refund orders affected by stock errors."
      },
      {
        "heading": "3. Product details",
        "body": "We aim to show frame colour, finish, and shape accurately, but screens vary. Lens prescriptions are glazed to the details you provide."
      },
      {
        "heading": "4. Payment",
        "body": "Prices are listed in Ghana Cedis. Prescription lenses are added when you order. Payment is by Mobile Money, cash, or card on request."
      },
      {
        "heading": "5. Returns",
        "body": "Returns and exchanges follow the policy on the Returns page. Frames must be unworn and in original condition."
      },
      {
        "heading": "6. Contact",
        "body": "Questions about these terms can be sent to hello@visionspacegh.gh."
      }
    ]
  },
  "privacy": {
    "eyebrow": "Privacy",
    "title": "Privacy Policy",
    "lastUpdated": "1 June 2026",
    "sections": [
      {
        "heading": "What we collect",
        "body": "We collect the details needed to process orders and support customers: name, phone, delivery address, prescription details where relevant, and order history."
      },
      {
        "heading": "How we use it",
        "body": {
          "intro": "We use your information to:",
          "bullets": [
            "Prepare and deliver orders.",
            "Glaze lenses to your prescription.",
            "Send order updates.",
            "Respond to messages.",
            "Share new drops only when you opt in."
          ]
        }
      },
      {
        "heading": "Who we share it with",
        "body": "We share data only with the delivery and payment partners required to fulfil your order."
      },
      {
        "heading": "Your choices",
        "body": "You can ask to access, correct, or delete your information by messaging hello@visionspacegh.gh."
      }
    ]
  },
  "shipping": {
    "eyebrow": "Shipping",
    "title": "Delivery and Pickup",
    "lastUpdated": "1 June 2026",
    "sections": [
      {
        "heading": "Accra delivery",
        "body": "We deliver across Accra. In-stock frames usually go out within one to two days; rates are confirmed when you order."
      },
      {
        "heading": "Pickup",
        "body": "Pickup is available in Kumasi. Message us first to confirm your pair is ready."
      },
      {
        "heading": "Outside Accra",
        "body": "Regional delivery is handled by partner couriers, with rates and timing confirmed at order."
      }
    ]
  },
  "returns": {
    "eyebrow": "Returns",
    "title": "Returns and Exchanges",
    "lastUpdated": "1 June 2026",
    "sections": [
      {
        "heading": "Exchange window",
        "body": "Unworn frames in original condition can be exchanged within 3 days of delivery or pickup."
      },
      {
        "heading": "Prescription lenses",
        "body": "Prescription-glazed lenses are made to order and cannot be returned unless faulty or glazed in error."
      },
      {
        "heading": "Damaged items",
        "body": "Send photos and your order details within 48 hours so we can make it right."
      }
    ]
  },
  "accessibility": {
    "eyebrow": "Accessibility",
    "title": "Accessibility Statement",
    "lastUpdated": "1 June 2026",
    "sections": [
      {
        "heading": "Our commitment",
        "body": "We want Vision Space to be usable by as many people as possible and aim for WCAG 2.1 AA standards."
      },
      {
        "heading": "What we test",
        "body": {
          "intro": "We focus on:",
          "bullets": [
            "Readable contrast.",
            "Keyboard navigation.",
            "Clear labels for controls and imagery.",
            "Layouts that work across mobile and desktop."
          ]
        }
      },
      {
        "heading": "Reporting issues",
        "body": "Message hello@visionspacegh.gh and we'll respond as soon as we can."
      }
    ]
  },
  "account": {
    "loginEyebrow": "Welcome back",
    "loginTitle": "Sign in to Vision Space",
    "loginSubtitle": "Track orders, manage addresses, and return to saved checkout details.",
    "signupEyebrow": "Join Vision Space",
    "signupTitle": "Create your Vision Space account",
    "signupSubtitle": "Save your details, track orders, and check out faster when new frames drop.",
    "accountEyebrow": "Your account",
    "accountTitle": "Welcome back"
  },
  "contactPage": {
    "eyebrow": "Contact",
    "title": "Talk to Vision Space.",
    "body": "Frame fit, prescriptions, order support, or collaborations — send a note and we'll reply soon.",
    "reasons": [
      "Frame fit",
      "Prescription help",
      "Order issue",
      "Exchange",
      "Collaboration"
    ],
    "directLines": [
      {
        "label": "WhatsApp",
        "value": "+233 59 888 2009",
        "href": "https://wa.me/233598882009"
      },
      {
        "label": "Phone",
        "value": "+233 59 888 2009",
        "href": "tel:+233598882009"
      },
      {
        "label": "Email",
        "value": "hello@visionspacegh.gh",
        "href": "mailto:hello@visionspacegh.gh"
      }
    ]
  },
  "trackOrder": {
    "eyebrow": "Track an order",
    "title": "Where are your frames?",
    "body": "Enter your order number and phone to see the latest status."
  },
  "footer": {
    "blurb": "Vision Space — an eye clinic near KNUST Campus, Kumasi, for eye tests, frames, and lenses.",
    "sitemap": [
      {
        "title": "Shop",
        "links": [
          {
            "label": "All products",
            "href": "/shop"
          },
          {
            "label": "Prescription",
            "href": "/categories/prescription"
          },
          {
            "label": "Futuristic",
            "href": "/categories/futuristic"
          },
          {
            "label": "Blue Light",
            "href": "/categories/blue-light"
          }
        ]
      },
      {
        "title": "Support",
        "links": [
          {
            "label": "Contact",
            "href": "/contact"
          },
          {
            "label": "Track an order",
            "href": "/track-order"
          },
          {
            "label": "Shipping",
            "href": "/shipping"
          },
          {
            "label": "Returns",
            "href": "/returns"
          },
          {
            "label": "FAQ",
            "href": "/faq"
          }
        ]
      },
      {
        "title": "Account",
        "links": [
          {
            "label": "Sign in",
            "href": "/login"
          },
          {
            "label": "Create account",
            "href": "/signup"
          },
          {
            "label": "Your orders",
            "href": "/account/orders"
          },
          {
            "label": "Settings",
            "href": "/account/settings"
          }
        ]
      },
      {
        "title": "Legal",
        "links": [
          {
            "label": "Terms of Service",
            "href": "/terms"
          },
          {
            "label": "Privacy Policy",
            "href": "/privacy"
          },
          {
            "label": "Accessibility",
            "href": "/accessibility"
          },
          {
            "label": "Sitemap",
            "href": "/sitemap-page"
          }
        ]
      }
    ],
    "poweredBy": {
      "label": "Cimplify",
      "href": "https://www.cimplify.io/"
    }
  },
  "llms": {
    "summary": "Vision Space — an eye clinic near KNUST Campus, Kumasi, for eye tests, frames, and lenses."
  },
  "mock": {
    "seed": "fashion",
    "businessId": "bus_visionspacegh"
  },
  "assets": {
    "logo": "https://res.cloudinary.com/dzykdnbvb/raw/upload/v1782664184/stage4/visionspacegh/logo.svg",
    "footerLogo": "https://res.cloudinary.com/dzykdnbvb/image/upload/v1782664188/stage4/visionspacegh/avatar.jpg",
    "hero": "https://res.cloudinary.com/dcc5ggnkc/image/upload/v1782453637/piustckyhcidu3usaa55.jpg",
    "heroVideo": "https://res.cloudinary.com/dcc5ggnkc/video/upload/v1782396828/jwadlxpq5dl7dtmsrxvo.mp4",
    "campaign": [
      "https://res.cloudinary.com/dcc5ggnkc/image/upload/v1782453637/piustckyhcidu3usaa55.jpg",
      "https://res.cloudinary.com/dcc5ggnkc/image/upload/v1782397287/nnudhxncil1iurojonlg.jpg",
      "https://res.cloudinary.com/dcc5ggnkc/image/upload/v1782397287/mypkwrjgq5etmjttwkzb.jpg",
      "https://res.cloudinary.com/dcc5ggnkc/image/upload/v1782454245/pv64w5hstpcbyq3ltfwn.jpg",
      "https://res.cloudinary.com/dcc5ggnkc/image/upload/v1782453469/aaggivzgiyfnoespzzw2.jpg",
      "https://res.cloudinary.com/dcc5ggnkc/image/upload/v1782397287/mypkwrjgq5etmjttwkzb.jpg"
    ],
    "hoodedSet": "https://res.cloudinary.com/dcc5ggnkc/image/upload/v1781852219/sfw0czastb6tkjkw47v0.jpg",
    "summer2026": [
      "https://res.cloudinary.com/dcc5ggnkc/image/upload/w_1600,q_auto,f_auto/v1782397347/vpqc2def1pfo1j4lnxvn.png",
      "https://res.cloudinary.com/dcc5ggnkc/image/upload/w_1600,q_auto,f_auto/v1782397348/exlwdxciti1fol6ncbxx.png",
      "https://res.cloudinary.com/dcc5ggnkc/image/upload/w_1600,q_auto,f_auto/v1782397346/aefp7ltn5oghf1owrye6.png",
      "https://res.cloudinary.com/dcc5ggnkc/image/upload/w_1600,q_auto,f_auto/v1782397345/wbdvsp4wuqzphtya36ig.png"
    ],
    "denimStory": "https://res.cloudinary.com/dcc5ggnkc/image/upload/v1782453469/aaggivzgiyfnoespzzw2.jpg"
  },
  "fashion": {
    "season": "2026 FRAME COLLECTION",
    "summer2026": {
      "eyebrow": "2026 collection",
      "title": "Prescription glasses.",
      "body": "Single-vision, bifocal, and progressive lenses glazed to your exact prescription and fitted into the frame you love.",
      "primaryCtaLabel": "Shop the collection",
      "primaryCtaHref": "/shop",
      "secondaryCtaLabel": "View lookbook",
      "secondaryCtaHref": "/collections/summer-2026",
      "signalEyebrow": "New in",
      "signalTitle": "Three frames. One clear look.",
      "imageKicker": "2026",
      "lookLabel": "Frame",
      "yearMark": "2026"
    },
    "campaignTitle": "See clearly, look sharp.",
    "campaignBody": "Frames built for movement and light — shapes that keep their edge from desk to dusk.",
    "categoryHighlight": {
      "eyebrow": "Shop by category",
      "title": "Find your frame.",
      "items": [
        {
          "slug": "prescription",
          "label": "Prescription",
          "blurb": "Glazed to your exact prescription and fitted to the frame you love.",
          "href": "/categories/prescription",
          "image": "https://res.cloudinary.com/dcc5ggnkc/image/upload/v1782453637/piustckyhcidu3usaa55.jpg"
        },
        {
          "slug": "futuristic",
          "label": "Futuristic",
          "blurb": "Bold, forward silhouettes for the road ahead.",
          "href": "/categories/futuristic",
          "image": "https://res.cloudinary.com/dcc5ggnkc/image/upload/v1782453469/aaggivzgiyfnoespzzw2.jpg"
        },
        {
          "slug": "blue-light",
          "label": "Blue light blocking",
          "blurb": "Screen-day comfort that filters the glare, all day.",
          "href": "/categories/blue-light",
          "image": "https://res.cloudinary.com/dcc5ggnkc/image/upload/v1782454245/pv64w5hstpcbyq3ltfwn.jpg"
        }
      ]
    },
    "seenBy": {
      "eyebrow": "Vision Space",
      "title": "Worn by the culture",
      "people": [
        {
          "role": "Prescription",
          "name": "Everyday optical",
          "image": "https://res.cloudinary.com/dcc5ggnkc/image/upload/v1782453468/zrtfpjieyq1ks1ydivqe.jpg"
        },
        {
          "role": "Blue light",
          "name": "Screen-day comfort",
          "image": "https://res.cloudinary.com/dcc5ggnkc/image/upload/v1782453468/v12wvmsoavepamencymx.jpg"
        },
        {
          "role": "Futuristic",
          "name": "Statement shades",
          "image": "https://res.cloudinary.com/dcc5ggnkc/image/upload/v1782453469/yvojtaua1fvkdshh7j3k.jpg"
        }
      ]
    },
    "mensTitle": "Men's frames",
    "mensBody": "Clean optical shapes, sharp metals, and everyday frames built to be worn daily.",
    "womensTitle": "Women's frames",
    "womensBody": "Cat-eyes, soft rounds, and statement colour — frames made to be noticed.",
    "denimTitle": "Future-facing",
    "denimBody": "Sculpted wraps and shields with an edge — the frames that turn heads after dark.",
    "accessoriesTitle": "Complete the look",
    "accessoriesBody": "Cases, microfibre cloths, cords, and lens care to keep every frame sharp.",
    "socialHandle": "@visionspacegh_"
  }
};
